""" My search criterion """
 
criterion = ["Detective Comics",
            "Batman",
            "Batman Beyond",
            "Harley",
            "Joker",
            "Nightwing",
            "Justice League",
            "Justice League Dark",
            "Justice League Odessey",
            "Birds of Prey",
            "Batgirl",
            "Titans",
            "Red Hood",
            "Batwoman",
            "Catwoman",
            "Suicide Squad",
            "Super Sons",
            "Teen Titans",
            "Doomsday Clock",
            "Robin",
            "Bane",
            "Manhattan",
            "Bruce",
            "Selina",
            "Tim Drake",
            "Stephanie Brown",
            "Orphan",
            "Cassandra Cain",
            "Kate Kane",
            "Dick Grayson",
            "Jim Gordon",
            "Mother Panic",
            "Duke Thomas",
            "Scott Snyder",
            "Tom King",
            "Heroes in Crisis",
            "Batman: Damned",
            "Batman: Kings of Fear", 
            "Heroes in Crisis",
            "Old Lady Harley",
            "Batman and the Outsiders",
            "Black Label"]
